name: alc_mobile_app
description: "Tools app for makro stroe 30"
publish_to: 'none'

version: 4.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.2.0
  firebase_database: ^11.0.3
  firebase_analytics: ^11.2.0
  firebase_auth: ^5.1.2
  firebase_messaging: ^15.0.4
  firebase_storage: ^12.1.1
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_screenutil: ^5.9.3
  flutter_barcode_scanner: "^2.0.0"
  intl: ^0.19.0
  flutter_keyboard_visibility: ^6.0.0
  package_info_plus: ^8.0.1
  fluttertoast: ^8.2.6
  http: ^1.2.1
  syncfusion_flutter_barcodes: ^26.2.8
  flutter_speed_dial: ^7.0.0
  url_launcher: ^6.3.0
  audioplayers: ^6.0.0
  image_picker: ^1.1.2
  video_player: ^2.9.1
  cloud_firestore: ^5.1.0
  file_picker: ^8.0.6
  photo_view: ^0.15.0
  form_field_validator: ^1.1.0
  webview_flutter: ^4.8.0
  sembast: ^3.7.1+3
  path: ^1.9.0
  path_provider: ^2.1.3
  flutter_svg: ^2.0.10+1
  device_info: ^2.0.0
  loader_overlay: ^4.0.0
  dio: ^5.5.0+1
  mobile_scanner: ^5.1.1
  permission_handler: ^11.3.1
  uuid: ^4.4.2
  flutter_slidable: ^3.1.1
  rxdart: ^0.28.0
  vibration: ^1.9.0
  badges: ^3.1.2 #
  flutter_local_notifications: ^17.2.1+2
  cached_network_image: ^3.4.0

  cupertino_icons: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/icon/

  fonts:
    - family: Kanit
      fonts:
        - asset: fonts/Kanit-Thin.ttf
          weight: 100
        - asset: fonts/Kanit-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Kanit-ExtraLight.ttf
          weight: 200
        - asset: fonts/Kanit-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Kanit-Light.ttf
          weight: 300
        - asset: fonts/Kanit-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Kanit-Regular.ttf
          weight: 400
        - asset: fonts/Kanit-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Kanit-Medium.ttf
          weight: 500
        - asset: fonts/Kanit-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Kanit-SemiBold.ttf
          weight: 600
        - asset: fonts/Kanit-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Kanit-Bold.ttf
          weight: 700
        - asset: fonts/Kanit-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Kanit-ExtraBold.ttf
          weight: 800
        - asset: fonts/Kanit-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Kanit-Black.ttf
          weight: 900
        - asset: fonts/Kanit-BlackItalic.ttf
          weight: 900
          style: italic

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo-alc-mobile-v7.png"